[package]
name = "pywebnn_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "pywebnn_rust"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
pyo3 = { version = "0.21", features = ["extension-module"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tch = "0.17"
